### PR TITLE
Updated for MC 1.21.0

### PR DESCRIPTION
**Pull request by davepusey**
Did a quick update to get this working for 1.21.0 (tested in rc1)

### CODE REVIEW

**Comment by 44Nifty** [comment]
Can someone commit this already?!

**Comment by 44Nifty** [comment]
Please commit this, I need this DP on 1.21 and I can't download from the pull request

**Comment by Wendelstein7** [comment]
I can confirm it works, thanks @davepusey !

**Comment by GoldenDelicios** [comment]
Thank you guys. I'll merge this now.

**Pull request merged**
